import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import styles from '@/styles/Buymed.module.css'
import Ex1 from '@/components/ex1'
import Ex2 from '@/components/ex2'
import Ex3 from '@/components/ex3'
import Ex5 from '@/components/ex5'
import Ex6 from '@/components/ex6'

const inter = Inter({ subsets: ['latin'] })

export default function App() {
  return (
    <>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Training Frontend</h1>
        <center>
        </center>
        <div className={styles.grid}>
          
          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 1: State Button
            </h3>
            <Ex1></Ex1>
          </div>

          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 2: Child Component
            </h3>
            <Ex2 value1={"Buymed"} value2={"ThuocSi"}></Ex2>
          </div>

          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 3: Form
            </h3>
            <Ex3></Ex3>
          </div>
          
          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 4: Add styles
            </h3>
            Added style button, grid, responsive and custom class like: main, exercise
          </div>

          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 5: Call API by legacy lib
            </h3>
            <Ex5></Ex5>
          </div>

          <div className={styles.exercise}>
            <h3 className={inter.className}>
              Exercise 6: Integrating Axios into your React project
            </h3>
            <Ex6></Ex6>
          </div>

        </div>
      </main>
    </>
  )
}